# Generated by Django 3.2.3 on 2021-07-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('rut', models.CharField(max_length=13, verbose_name='Rut Cliente')),
                ('nombreCliente', models.CharField(max_length=30, verbose_name='Nombre Cliente')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('nombreUsuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Usuario')),
                ('password', models.CharField(blank=True, max_length=12, null=True, verbose_name='Password')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='Nombre del producto')),
                ('color', models.CharField(max_length=15, verbose_name='Color Producto')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('ideDescuento', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Descuento')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
